### ISSUE TITLE
serial is not incrementing

### ISSUE THREAD

**Issue by eriktigerholm** [nolanbrown/ios-cert-enrollment#1]
I have also been struggling with Over the Air to iOS and I your code helped me alot.

I got the error that the profile can not be encrypted because of missing private key. It was because I did not increment the serial in the certificate. iOS discards the certificate if it has an other with higher or equal serial.

I see that you set the serial to one in your code.

**Comment by nolanbrown** [comment]
Sorry, I didn't get the GH notification email for this.

Thanks for the heads up on this. I was incrementing in the code I was running live but I must have left that out of this.

**Comment by nolanbrown** [comment]
There was an issue with the serial number and the webclip. The webclip now installs correctly and I've added a new example server that should help with the implementation details.
